### ISSUE TITLE
tables/D1b not found.

### ISSUE THREAD

**Issue by NagarajSelvaraj** [NitishaS-812k/Mp3-Encoder#2]
How to download tables/D1b

**Comment by NitishaS-812k** [comment]
Hi, 
I have pushed the missing folder required to run this program, if this solves your issue consider closing this issue. If you face any more issues do open a new issue, I would be glad to sort them out.
Thank you

> How to download tables/D1b

**Comment by NagarajSelvaraj** [comment]
Hi,
Thanks for sharing files.
